name: Run Tests for Modified Microservices

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Detect modified microservices
        id: changes
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "Pull request detected."
            git fetch origin main
            diff_base="origin/main"
          else
            echo "Push detected."
            diff_base="${{ github.event.before }}"
            if [[ -z "$diff_base" ]]; then
              echo "No previous commit found, using HEAD~1"
              diff_base="HEAD~1"
            fi
          fi

          modified_files=$(git diff --name-only "$diff_base" ${{ github.sha }})

          echo "Modified files:"
          echo "$modified_files"

          if [[ -z "$modified_files" ]]; then
            echo "No modified files detected."
            echo "services=" >> $GITHUB_OUTPUT
            exit 0
          fi

          services=$(echo "$modified_files" | sed -n 's|^\([^/]*\)/.*|\1|p' | sort -u | grep -E '.+-microservice$' | uniq | tr '\n' ' ')
         
          echo "Detected services: $services"
          echo "services=$services" >> $GITHUB_OUTPUT

      - name: Run tests on modified services
        if: ${{ steps.changes.outputs.services != '' }}
        run: |
          for service in ${{ steps.changes.outputs.services }}; do
            echo "Testing $service..."
            cd $service
            mvn clean verify
            cd -
          done

      - name: Run fallback action if no microservices modified
        if: ${{ steps.changes.outputs.services == '' }}
        run: |
          echo "No microservices modified."
