name: Run Tests for Modified Microservices

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Detect modified microservices
        id: changes
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "Pull request detected."
            git fetch origin main
            diff_base="origin/main"
          else
            echo "Push detected."
            diff_base="${{ github.event.before }}"
          fi

          services=$(git diff --name-only $diff_base ${{ github.sha }} | grep -oE '^[^/]+(?=/)' | sort -u | grep -E '(doctor-microservice|hospital-microservice|patient-microservice|test-microservice)' | uniq | tr '\n' ' ')
          
          echo "services=$services" >> $GITHUB_OUTPUT

      - name: Run tests on modified services
        if: ${{ steps.changes.outputs.services != '' }}
        run: |
          for service in ${{ steps.changes.outputs.services }}; do
            echo "Testing $service..."
            cd $service
            mvn clean verify
            cd -
          done
