name: Run Tests for Modified Microservices

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Detect modified microservices
        id: changes
        run: |
          echo "services=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -oE '^[^/]+(?=/)' | sort -u | grep -E '(doctor-microservice|hospital-microservice|patient-microservice|test-microservice)' | uniq | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Run tests on modified services
        run: |
          for service in ${{ steps.changes.outputs.services }}; do
            echo "Testing $service..."
            cd $service
            mvn clean verify
            cd -
          done
